<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="logo.png">
        </div>

        <div class="row">
          <div class="col text-center">
            <h2>Cadastro realizado com sucesso</h2>
          </div>
        </div>

        <div class="row">
          <div class="col p-5">
            <a href="/" class="btn btn-info btn-block">Clique aqui para fazer login!</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  