
    <div class="container d-flex justify-content-center">    

      <div class="col-md-8 mt-3 card-abrir-chamado">
          <div class="card">
            <div class="card-header">
              Abertura de chamado
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <form method="post" action="/registra_chamado">
                    <div class="form-group">
                      <label>Título</label>
                      <input name="titulo" type="text" class="form-control" placeholder="Título">
                    </div>
                    
                    <div class="form-group">
                      <label>Categoria</label>
                      <select name="categoria" class="form-control">
                        <option>Criação Usuário</option>
                        <option>Impressora</option>
                        <option>Hardware</option>
                        <option>Software</option>
                        <option>Rede</option>
                        <option>Desconhecido</option>
                      </select>
                    </div>
                    
                    <div class="form-group">
                      <label>Descrição</label>
                      <textarea name="descricao" class="form-control" rows="3"></textarea>
                    </div>
                    <? if($this->view->abrir) { ?>
                      <div class="row">
                        <div class="col">
                          <span class="text text-danger animate__animated animate__headShake position-absolute">Preencha todos os campos.</span>
                        </div>
                      </div>
                    <? } ?>
                    <div class="row mt-5">
                      <div class="col-6">
                        <a class="btn btn-lg btn-warning btn-block" href="/home">Voltar</a>
                      </div>

                      <div class="col-6">
                        <button class="btn btn-lg btn-info btn-block" type="submit">Abrir</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
        </div>
        <div class="col-6 col-md-4 col-xl-3 comunicacao">
          <?php foreach($this->view->adm as $key=>$dados){ ?>
            <input class="col-1 btn-chat-cliente" value="<?=$dados['nome']?>"></input>
          <? } ?>

          <div class="chat bg-light rounded">
            <div class="bg-light text-center menu-chat">
              <small class="text-info">Chat</small>
              <i class="fas fa-times fa-x1 fecha-chat text-right"></i>
            </div>
            
            <div class="col-12 h-100 chat-pessoal">
              <div class="conversa-nomeCliente"></div>
              <i class="fas fa-times fa-x1 fecha-conversa rounded text-right"></i>
              <div class="conversa m-0">

              </div>
              <form>
		            <input class="d-none input-nome" type="text" name="nome" value="<?= $_SESSION['nome'] ?>">
                <input class="d-none input-destino" type="text" name="nome" value="adminstrador">
                <input type="text" name="mensagem" class="form-control input-conversa m-0 p-0 col-8" placeholder="mensagem">
                <input class="col-3 input-enviar " type="submit" value="Enviar">
              </form>
            </div>
          </div>
        </div>
    </div>
    