<div class="container d-flex justify-content-center align-content-center column" style="margin-top: 10%;">    
        <div class="col-md-6 card-home">
          <div class="card">
            <div class="card-header">
              Menu
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-12 d-flex justify-content-center">
                  <a class="pai2" href="/consultar_chamado_adm">
                    <img class="img-icon2" src="../formulario_consultar_chamado.png" width="70" height="70">
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>