<div class="container d-flex justify-content-center">    
        <div class="col-8 mt-3 card-consultar-chamado">
          <div class="card">
            <div class="card-header">
              Consulta de chamados
            </div>
            
            <div class="card-body">
              <?php foreach($this->view->dadosChamado as $key=>$dados){ ?>
              <div class="card mb-3 bg-light">
                <div class="card-body">
                    <p class="card-subtitle font-italic float-right position-relative"><?= $dados['nome'] ?><p>
                    <div class="float-left pt-0 mt-0 position-relative">
                        <h5 class="card-title"><?= $dados['titulo'] ?></h5>
                        <h5 class="card-subtitle mb-2 text-muted"><?= $dados['categoria'] ?></h6>
                        <p class="card-text"><?= $dados['descricao'] ?></p>
                    </div>     
                </div>
              </div>
              <? } ?>
              <div class="row mt-5">
                <div class="col-6">
                  <a class="btn btn-lg btn-warning btn-block" href="/home">Voltar</a>
                </div>
              </div>
            </div>
          </div>
        </div>
  </div>

  
