<div class="container d-flex justify-content-center" style="padding-top: 5%;">    
        <div class="col-md-8 mt-3 card-consultar-chamado">
          <div class="card">
            <div class="card-header">
              <p class="pt-2 m-0 col-5 float-left">Consulta de chamados</p>
              <select id="nome" class="form-control p-0 m-0 col-3 float-left">
                <option>Clientes</option>
                
                <?php
                  foreach($this->view->clientes as $key => $dados){?>
                    <option><?=$dados['nome'] ?></option>
                <?php } ?>
              </select>
              <div class="col-1 float-left"></div>
              <select id="categoria" class="form-control p-0 m-0 col-3 float-left">
                <option>Categorias</option>
                <option>Impressora</option>
                <option>Hardware</option>
                <option>Software</option>
                <option>Rede</option>
                <option>Desconhecido</option>
              </select>
            </div>
            <div class="card-body">
              <div class="todosClientes position-relative">
                <?php $possui_dados_ainda = 0; foreach($this->view->dadosChamado as &$dados){ 
                          if($dados['status'] == 'pendente'){
                              $possui_dados_ainda += 1;
                          }
                      }
                ?>
                <?php if($possui_dados_ainda != 0){ foreach($this->view->dadosChamado as &$dados){ ?>
                  <div class="scrollRevela card mb-3 bg-light position-relative">
                    <div class="card-body pb-0 m-0">
                        <p class="card-subtitle font-italic float-right position-relative p-0 mb-xl-0 mb-4 relative-name-adm"><?= $dados['nome'] ?></p>
                        <div class="float-left position-relative relative-card-adm col-12">
                            <h5 class="card-title"><?= $dados['titulo'] ?></h5>
                            <h6 class="card-subtitle mb-2 text-muted"><?= $dados['categoria'] ?></h6>
                            <p class="card-text"><?= $dados['descricao'] ?></p>
                            <form>
                              <div class="form-check m-0 p-0">
                                <label class="status-font" for="status">Marcar como concluído:</label><br>
                                <span><button type="button" value="realizado<?= $dados['id'] ?>" name="status" class="status btn btn-info btn-sm">confirmar</button><small class="font-italic float-right text-dark mr-0 pr-0"><?= $dados['data_mod'] ?></small></span>
                              </div>
                            </form>                           
                        </div>     
                    </div>
                  </div>
                  <?php }
                  }else{ ?>
                    <div class="py-5 text-center d-flex pelaCategoria align-content-center justify-content-center position-relative animate__animated animate__fadeIn animate_duracao">
                      <h2>Nenhum cliente possui chamados no momento.</h2>
                    </div>
                   
                  <?php } ?>
              </div>
              <span class="clienteAtual">

              </span>
              <span class="categoriaAtual">
                
              </span>
                <div class="row mt-5">
                  <!-- <div class="col-12 col-xl-6 pb-2 pb-xl-0">
                    <a class="btn btn-lg btn-warning btn-block" href="/home">Voltar</a>
                  </div> -->
                  <div class="col-12 col-xl-6">
                    <a class="btn btn-lg btn-info btn-block" href="/consultar_chamados_realizados_adm">Chamados concluidos</a>
                  </div>
                </div>
            </div> 
          </div>
        </div>
        
  </div>