  <div class="container d-flex justify-content-center">    
        <div class="col-md-8 mt-3 card-consultar-chamado">
          <div class="card">
            <div class="card-header">
              Consulta de chamado
            </div>
            
            <div class="card-body">
              <?php foreach($this->view->dadosChamado as $key=>$dados){ ?>
              <div class="card mb-3 bg-light position-relative animate__animated animate__fadeIn animate_duracao">
                <div class="card-body">
                  <h5 class="card-title"><?= $dados['titulo'] ?></h5>
                  <h6 class="card-subtitle mb-2 text-muted"><?= $dados['categoria'] ?></h6>
                  <p class="card-text"><?= $dados['descricao'] ?></p>
                  <? if($dados['status'] == 'realizado') { ?>
                    <small class="card-text text-success"><?= $dados['status'] ?></small>
                  <? } else {?>
                    <small class="card-text text-danger"><?= $dados['status'] ?></small>
                  <? } ?>
                </div>
              </div>
              <? } ?>
              <div class="row mt-5">
                <div class="col-6">
                  <a class="btn btn-lg btn-warning btn-block" href="/home">Voltar</a>
                </div>
              </div>
            </div>
          </div>
        </div>
  </div>
