<div class="container d-flex justify-content-center" style="padding-top: 5%;">    
        <div class="col-12 mt-3 card-consultar-chamado">
          <div class="card">
            <div class="card-header">
              <p class="pt-2 m-0 col-12 float-left">Consulta de chamados realizados</p>
            </div>
            <div class="card-body p-0">
              <div class="todosClientes mt-md-5 mt-2 position-relative d-flex justify-content-around align-content-around flex-wrap p-0">
                <?php foreach($this->view->dadosChamado as $key=>$dados){ ?>
                  
                  <div class="scrollRevela card col-md-5 col-11 bg-light position-relative mb-md-5 mb-2">
                    <div class="card-body pb-0 m-0">
                        
                        <div class="float-left d-flex p-0 m-0 mt-md-4 mt-3 align-content-center align-items-center flex-column relative-card-adm col-12">
                            <h5 class="card-title"><?= $dados['titulo'] ?></h5>
                            <h6 class="card-subtitle mb-md-2 mb-1 text-muted"><?= $dados['categoria'] ?></h6>
                            <p class="card-text"><?= $dados['descricao'] ?></p>                        
                        </div>
                    </div>                        
                    <p class="card-subtitle mt-3 font-italic position-relative pos-adm-name-realizado p-0 m-0 col-10"><?= $dados['nome'] ?><small class="font-italic float-right text-dark mr-0 pr-0"><?= $dados['data_mod'] ?></small></p>     
                  </div>
                <? } ?>
              </div>
                <div class="row">
                  <div class="col-4 p-3 ml-5">
                    <a class="btn btn-lg btn-warning btn-block" href="/consultar_chamado_adm">Voltar</a>
                  </div>
                </div>
            </div> 
          </div>
        </div>
  </div>

  
