  <div class="container d-flex justify-content-center" style="padding-top: 5%;">    
        <div class="col-md-8 mt-3 card-consultar-chamado">
          <div class="card">
            <div class="card-header">
              Consulta de chamado
            </div>
            
            <div class="card-body">
              <?php $possui_dados_ainda = 0; foreach($this->view->dadosChamado as $key=>$dados){ 
                      if($dados['status'] != ''){
                          $possui_dados_ainda += 1;
                      }
                  }
              ?>
              <?php if($possui_dados_ainda != 0){ foreach($this->view->dadosChamado as $key=>$dados){ ?>
              <div class="scrollRevela card mb-3 bg-light">
                <div class="card-body">
                  <h5 class="card-title"><?= $dados['titulo'] ?></h5>
                  <h6 class="card-subtitle mb-2 text-muted"><?= $dados['categoria'] ?></h6>
                  <p class="card-text"><?= $dados['descricao'] ?></p>
                  <?php if($dados['status'] == 'realizado') { ?>
                    <small class="ml-0 pl-0 card-text text-success col-12"><?= $dados['status'] ?><small class="font-italic float-right text-dark mr-0 pr-0"><?= $dados['data_mod'] ?></small></small>
                  <?php } else {?>
                    <small class="ml-0 pl-0 card-text text-danger col-12"><?= $dados['status'] ?><small class="font-italic float-right text-dark mr-0 pr-0"><?= $dados['data_mod'] ?></small></small>
                  <?php } ?>
                </div>
              </div>
              <?php } ?>
              <?php }else{ ?>
                <div class="py-5 text-center d-flex pelaCategoria align-content-center justify-content-center position-relative animate__animated animate__fadeIn animate_duracao">
                  <h2>Você não realizou pedidos ainda.</h2>
                </div>
              <?php } ?>
              <div class="row mt-5">
                <div class="col-6">
                  <a class="btn btn-lg btn-warning btn-block" href="/home">Voltar</a>
                </div>
              </div>
            </div>
          </div>
        </div>
  </div>
