<div  onload="ajax()" class="container d-flex justify-content-center">    
        <div class="col-md-8 mt-3 card-consultar-chamado">
          <div class="card">
            <div class="card-header">
              <p class="pt-2 m-0 col-5 float-left">Consulta de chamados</p>
              <select id="nome" class="form-control p-0 m-0 col-3 float-left">
                <option>Clientes</option>
                <?php foreach($this->view->clientes as $key=>$dados){ ?>
                  <option><?= $dados['nome'] ?></option>
                <? } ?>
              </select>
              <div class="col-1 float-left"></div>
              <select id="categoria" class="form-control p-0 m-0 col-3 float-left">
                <option>Categorias</option>
                <option>Impressora</option>
                <option>Hardware</option>
                <option>Software</option>
                <option>Rede</option>
                <option>Desconhecido</option>
              </select>
            </div>
            <div class="card-body">
              <div class="todosClientes position-relative">
                <?php $possui_dados_ainda = 0; foreach($this->view->dadosChamado as $key=>$dados){ 
                          if($dados['status'] == 'pendente'){
                              $possui_dados_ainda += 1;
                          }
                      }
                ?>
                <?php if($possui_dados_ainda != 0){ foreach($this->view->dadosChamado as $key=>$dados){ ?>
                  <div class="scrollRevela card mb-3 bg-light position-relative">
                    <div class="card-body pb-0 m-0">
                        <p class="card-subtitle font-italic float-right position-relative p-0 m-0 relative-name-adm"><?= $dados['nome'] ?></p>
                        <div class="float-left position-relative relative-card-adm col-12">
                            <h5 class="card-title"><?= $dados['titulo'] ?></h5>
                            <h6 class="card-subtitle mb-2 text-muted"><?= $dados['categoria'] ?></h6>
                            <p class="card-text"><?= $dados['descricao'] ?></p>
                            <form>
                              <div class="form-check m-0 p-0">
                                <label class="status-font" for="status">Marcar como concluído:</label><br>
                                <span><button type="button" value="realizado<?= $dados['id'] ?>" name="status" class="status btn btn-info btn-sm">confirmar</button><small class="font-italic float-right text-dark mr-0 pr-0"><?= $dados['data_mod'] ?></small></span>
                              </div>
                            </form>                           
                        </div>     
                    </div>
                  </div>
                  <? }
                  }else{ ?>
                    <div class="py-5 text-center d-flex pelaCategoria align-content-center justify-content-center position-relative animate__animated animate__fadeIn animate_duracao">
                      <h2>Nenhum cliente possui pedidos no momento.</h2>
                    </div>
                   
                  <? } ?>
              </div>
              <span class="clienteAtual">

              </span>
              <span class="categoriaAtual">
                
              </span>
                <div class="row mt-5">
                  <div class="col-6">
                    <a class="btn btn-lg btn-warning btn-block" href="/home">Voltar</a>
                  </div>
                  <div class="col-6">
                    <a class="btn btn-lg btn-info btn-block" href="/consultar_chamados_realizados_adm">Chamados concluidos</a>
                  </div>
                </div>
            </div> 
          </div>
        </div>
        <div class="col-3 comunicacao">
          <button class="col-1 btn btn-info btn-chat">Chat</button>
          
          <div class="chat bg-light rounded">
            <div class="bg-light text-center menu-chat">
              <small class="text-info">Chat</small>
              <i class="fas fa-times fa-x1 fecha-chat text-right"></i>
            </div>
            
            <?php foreach($this->view->clientes as $key=>$dados){ ?>
              <div class=" text-center p-0 m-0 chat-clientes">
                <input type="button" class="col-12 m-0 py-3 nomes-chat" value="<?=$dados['nome']?>">
              </div>
            <? } ?>
            
            <div class="col-12 h-100 chat-pessoal">
              <div class="conversa-nomeCliente"></div>
              <i class="fas fa-times fa-x1 fecha-conversa rounded text-right"></i>
              <div class="conversa m-0 p-0">
                

              </div>
              <form>
		            <input class="d-none input-nome" type="text" name="nome" value="administrador">
                <input class="d-none input-destino" type="text" name="nome" value="">
                <input type="text" name="mensagem" class="form-control input-conversa m-0 p-0 col-8" placeholder="mensagem">
                <input class="col-3 input-enviar " type="submit" value="Enviar">
              </form>
              
            </div>
          </div>
        </div>
  </div>