<div class="container d-flex justify-content-center" style="padding-top: 15%;">    
        <div class="col-md-12 mt-3 card-consultar-chamado">
          <div class="card">
            <div class="card-header">
              <p class="pt-2 m-0 col-12 float-left">Dashboard</p>
            </div>
            <div class="card-body">
              <div class="todosClientes position-relative">
                  <div class="row mb-3">
                    <div class="col-md-4">
                      <div class="card">
                        <div class="card-header">
                          Número de Chamados Pendentes
                        </div>
                        <div class="card-body">
                          <?php foreach($this->view->numChamPen as $key=>$dados){ ?>
                            <h5 class="card-title"><?= $dados['0']?></h5>
                          <?php break;} ?>
                        </div>
                      </div>
                    </div>

                    <div class="col-md-4">
                      <div class="card">
                        <div class="card-header">
                          Total de Chamados
                        </div>
                        <div class="card-body">
                          <?php foreach($this->view->numCham as $key=>$dados){ ?>
                            <h5 class="card-title"><?= $dados?></h5>
                          <?php break;} ?>
                        </div>
                      </div>
                    </div>

                    <div class="col-md-4">
                      <div class="card">
                        <div class="card-header">
                          Total de Clientes
                        </div>
                        <div class="card-body">
                          <?php foreach($this->view->numClientes as $key=>$dados){ ?>
                            <h5 class="card-title"><?= $dados['0']?></h5>
                          <?php break;} ?>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
            </div> 
          </div>
        </div>
  </div>