<div  onload="ajax()" class="container d-flex justify-content-center" style="padding-top: 5%;">    
        <div class="col-md-8 mt-3 card-consultar-chamado">
          <div class="card">
            <div class="card-header">
              <p class="pt-2 m-0 col-12 float-left">Consulta de endereços <em>(clientes que já realizaram o primeiro chamado)</em></p>
            </div>
            <div class="card-body">
              <div class="todosClientes position-relative">
                <?php  foreach($this->view->dadosEndereco as $key=>$dados){?>
                  <div class="scrollRevela card mb-3 bg-light position-relative">
                    <div class="card-body pb-0 m-0">
                        <div class="float-left position-relative relative-card-adm col-12">
                            <div class="row form-group">
                                <div class="col-sm-12 pt-5">
                                    <h3><?= $dados['nome_usuario'] ?></h3>
                                </div>
                                <div class="col-sm-6">
                                    <p value="">CEP: <?= $dados['cep'] ?></p>
                                </div>
                                <div class="col-sm-12">
                                    <p><?= $dados['endereco']?> - <?= $dados['bairro'] ?>, <?= $dados['cidade']?>-<?= $dados['UF']?></p>
                                </div>
                                <div class="col-12">
                                    <p>Complemento: <?= $dados['complemento']?></p>
                                </div>
                            </div>
                        </div>     
                    </div>
                  </div>
                    <!-- <div class="py-5 text-center d-flex peloNome align-content-center justify-content-center position-relative animate__animated animate__fadeIn animate_duracao">
                      <h2>O cliente não realizou um chamado ainda.</h2>
                    </div> -->
                  <? } ?>
              </div>
            </div> 
          </div>
        </div>
        <div class="col-6 col-md-4 col-xl-3 comunicacao">
          <a class="col-1 btn-chat"><img src="../icons8-suporte-on-line-96.png" class="mx-auto" alt="chat com o suporte" width="50px" height="50px"></a>
          
          <div class="chat bg-light rounded">
            <div class="bg-light text-center menu-chat">
              <small class="text-info">Chat</small>
              <i class="fas fa-times fa-x1 fecha-chat text-right"></i>
            </div>
            
            <?php foreach($this->view->clientes as $key=>$dados){ ?>
              <div class=" text-center p-0 m-0 chat-clientes">
                <input type="button" class="col-12 m-0 py-3 nomes-chat" value="<?=$dados['nome']?>">
              </div>
            <? } ?>
            
            <div class="col-12 h-100 chat-pessoal">
              <div class="conversa-nomeCliente"></div>
              <i class="fas fa-times fa-x1 fecha-conversa rounded text-right"></i>
              <div class="conversa m-0">

              </div>
              <form>
		            <input class="d-none input-nome" type="text" name="nome" value="administrador">
                <input class="d-none input-destino" type="text" name="nome" value="">
                <input type="text" name="mensagem" class="form-control input-conversa m-0 pl-3 col-8" placeholder="mensagem">
                <input class="col-3 input-enviar " type="submit" value="Enviar">
              </form>
              
            </div>
          </div>
        </div>
  </div>