<div  onload="ajax()" class="container d-flex justify-content-center" style="padding-top: 5%;">    
        <div class="col-md-8 mt-3 card-consultar-chamado">
          <div class="card">
            <div class="card-header">
              <p class="pt-2 m-0 col-12 float-left">Consulta de endereços <em>(clientes que já realizaram o primeiro chamado)</em></p>
            </div>
            <div class="card-body">
              <div class="todosClientes position-relative">
                <?php foreach($this->view->dadosEndereco as $key=>$dados){?>
                  <div class="scrollRevela card mb-3 bg-light position-relative">
                    <div class="card-body pb-0 m-0">
                        <div class="float-left position-relative relative-card-adm col-12">
                            <div class="row form-group">
                                <div class="col-sm-12 pt-5">
                                    <h3><?= $dados['nome'] ?></h3>
                                </div>
                                <div class="col-sm-6">
                                    <p value="">CEP: <?= $dados['cep'] ?></p>
                                </div>
                                <div class="col-sm-12">
                                    <p><?= $dados['endereco']?> - <?= $dados['bairro'] ?>, <?= $dados['cidade']?>-<?= $dados['uf']?></p>
                                </div>
                                <div class="col-12">
                                    <p>Complemento: <?= $dados['complemento']?></p>
                                </div>
                            </div>
                        </div>     
                    </div>
                  </div>
                    <!-- <div class="py-5 text-center d-flex peloNome align-content-center justify-content-center position-relative animate__animated animate__fadeIn animate_duracao">
                      <h2>O cliente não realizou um chamado ainda.</h2>
                    </div> -->
                  <?php } ?>
              </div>
            </div> 
          </div>
        </div>
  </div>