<div class="container d-flex justify-content-center align-content-center column" style="margin-top: 10%;">    
      <div class="row">
        <div class="col-12 text-center mb-3">
          <h2>Olá, <?= $this->view->nome?>! Encaminhe seu pedido ou consulte os já feitos.</h2>
        </div>
        <div class="col-12 card-home">
          <div class="card">
            <div class="card-header">
              Menu
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-6 d-flex justify-content-center">
                  <a class="pai1" href="/abrir_chamado">
                    <img class="img-icon" src="../icons8-tarefa-96.png" width="96" height="96">
                  </a>
                </div>
                <div class="col-6 d-flex justify-content-center">
                  <a class="pai2" href="/consultar_chamado">
                    <img class="img-icon2" src="../icons8-tarefa-concluída-96.png" width="96" height="96">
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-6 col-md-4 col-xl-3 comunicacao">
          <?php foreach($this->view->adm as $key=>$dados){ ?>
            <input class="col-1 btn-chat-cliente" value="<?=$dados['nome']?>"></input>
          <? } ?>

          <div class="chat bg-light rounded">
            <div class="bg-light text-center menu-chat">
              <small class="text-info">Chat</small>
              <i class="fas fa-times fa-x1 fecha-chat text-right"></i>
            </div>
            
            <div class="col-12 h-100 chat-pessoal">
              <div class="conversa-nomeCliente"></div>
              <i class="fas fa-times fa-x1 fecha-conversa rounded text-right"></i>
              <div class="conversa m-0">

              </div>
              <form>
		            <input class="d-none input-nome" type="text" name="nome" value="<?= $_SESSION['nome'] ?>">
                <input class="d-none input-destino" type="text" name="nome" value="administrador">
                <input type="text" name="mensagem" class="form-control input-conversa m-0 p-0 col-8" placeholder="mensagem">
                <input class="col-3 input-enviar " type="submit" value="Enviar">
              </form>
            </div>
          </div>
        </div>
    </div>