<div class="container d-flex justify-content-center align-content-center column" style="margin-top: 10%;">    
      <div class="row">
        <div class="col-12 text-center mb-3">
          <h2>Olá, <?= $this->view->nome?>! Encaminhe seu pedido ou consulte os já feitos.</h2>
        </div>
        <div class="col-12 card-home">
          <div class="card">
            <div class="card-header">
              Menu
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-6 d-flex justify-content-center">
                  <a class="pai1" href="/abrir_chamado">
                    <img class="img-icon" src="../formulario_abrir_chamado.png" width="70" height="70">
                  </a>
                </div>
                <div class="col-6 d-flex justify-content-center">
                  <a class="pai2" href="/consultar_chamado">
                    <img class="img-icon2" src="../formulario_consultar_chamado.png" width="70" height="70">
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>