<html>
  <head>
    <meta charset="utf-8" />
    <title>App Help Desk</title>
    
    <link rel="icon" type="image/png" href="logo.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="estilo.css">
    <script src="https://kit.fontawesome.com/bf49d14db6.js" crossorigin="anonymous" defer></script>
    <meta name="theme-color" content="#4285f4">
    <script src="https://unpkg.com/scrollreveal"></script>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark position-fixed">
      <a class="navbar-brand" href="/home">
        <img src="logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        App Help Desk
      </a>
      
      <div class="nav-side-menu">
		    <i class="fa fa-bars fa-2x menu-hamburguer"></i>
        <i class="fas fa-times fa-2x menu-hamburguer-fechar"></i>
		      <div class="menu-content position-fixed bg-dark">
		            <ul class="menu-escolhas">
                    <img src="logo.png" width="80" height="80" class="d-flex justify-content-center mr-4 mb-4" alt="">
                  <?php if($_SESSION['nome'] == 'administrador') {?>
                    <li>
		                  <a href="/consultar_chamado_adm" class="nav-link">Chamados</a>
		                </li>
		                <li>
		                  <a href="/enderecos" class="nav-link">Endereços</a>
		                </li>
		                <li>
		                  <a href="/dashboard" class="nav-link">Dashboard de clientes</a>
		                </li>
                  <?php } ?>
                    <li>
		                  <a class="nav-link" href="/sair">Sair</a>
		                </li>
		            </ul>
		      </div>
		  </div>
    </nav>
    
    <?= $this->content() ?>

    <?php if($_SESSION['senha'] == "admadm"){ ?>

      <div class="col-6 col-md-4 col-xl-3 comunicacao">
        <a class="col-1 btn-chat"><img src="../icons8-suporte-on-line-96.png" class="mx-auto" alt="chat com o suporte" width="50px" height="50px"></a>
            
        <div class="chat bg-light rounded">
          <div class="bg-light text-center menu-chat">
            <small class="text-info">Chat</small>
            <i class="fas fa-times fa-x1 fecha-chat text-right"></i>
          </div>

          <?php foreach($this->view->clientes as $key => $dados) { ?>
            <div class=" text-center p-0 m-0 chat-clientes">
              <input type="button" class="col-12 m-0 py-3 nomes-chat" value="<?= $dados['nome']?>">
            </div>
          <?php } ?>
              
          <div class="col-12 h-100 chat-pessoal">
            <div class="conversa-nomeCliente"></div>
            <i class="fas fa-times fa-x1 fecha-conversa rounded text-right"></i>
            <div class="conversa m-0">

            </div>
            <form>
              <input class="d-none input-nome" type="text" name="nome" value="administrador">
              <input class="d-none input-destino" type="text" name="nome" value="">
              <input type="text" name="mensagem" class="form-control input-conversa m-0 pl-3 col-8" placeholder="mensagem">
              <input class="col-3 input-enviar" type="submit" value="Enviar">
            </form>
                
          </div>
        </div>
      </div>

    <?php }else { ?>

      <div class="col-6 col-md-4 col-xl-3 comunicacao">
        <input class="col-1 btn-chat-cliente btn" value="administrador"/>
        <img src="../icons8-suporte-on-line-96.png" width="50px" heigth="50px" class="img-chat">

        <div class="chat bg-light rounded">
          <div class="bg-light text-center menu-chat">
            <small class="text-info">Chat</small>
            <i class="fas fa-times fa-x1 fecha-chat text-right"></i>
          </div>
            
          <div class="col-12 h-100 chat-pessoal">
            <div class="conversa-nomeCliente"></div>
            <i class="fas fa-times fa-x1 fecha-conversa rounded text-right"></i>
            <div class="conversa m-0">

            </div>
            <form>
		          <input class="d-none input-nome" type="text" name="nome" value="<?= $_SESSION['nome'] ?>">
              <input class="d-none input-destino" type="text" name="nome" value="administrador">
                
              <input type="text" name="mensagem" class="form-control input-conversa m-0 pl-3 col-8" placeholder="mensagem">
              <input class="col-3 input-enviar " type="submit" value="Enviar">
            </form>
            <input type="text" name="mensagem" class="form-control input-conversa-bot m-0 pl-3 col-8" placeholder="mensagem">
            <input class="col-3 input-enviar-bot " type="submit" value="Enviar">
          </div>
        </div>
      </div>
      
    <?php } ?>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="script.js" type="text/javascript" language="javascript"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
  </body>
</html>