<html>
  <head>
    <meta charset="utf-8" />
    <title>App Help Desk</title>
    
    <link rel="icon" type="image/png" href="logo.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="estilo.css">
    <script src="https://kit.fontawesome.com/bf49d14db6.js" crossorigin="anonymous" defer></script>
    <meta name="theme-color" content="#4285f4">
    <script src="https://unpkg.com/scrollreveal"></script>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark position-fixed">
      <a class="navbar-brand" href="/home">
        <img src="logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        App Help Desk
      </a>
      
      <div class="nav-side-menu">
		    <i class="fa fa-bars fa-2x menu-hamburguer"></i>
        <i class="fas fa-times fa-2x menu-hamburguer-fechar"></i>
		      <div class="menu-content position-fixed bg-dark">
		            <ul class="menu-escolhas">
                  <?if($_SESSION['nome'] == 'administrador') {?>
		                <li>
		                  <a href="/enderecos" class="nav-link">Endereços</a>
		                </li>
		                <li>
		                  <a href="/dashboard" class="nav-link">Dashboard de clientes</a>
		                </li>
                  <? }else{ ?>
                    <li>
		                  <a href="/dados_cliente" class="nav-link">Meus dados</a>
		                </li>
                  <? }?>
                    <li>
		                  <a class="nav-link" href="/sair">Sair</a>
		                </li>
		            </ul>
		      </div>
		  </div>
    </nav>
    
    <?= $this->content() ?>

    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="script.js" type="text/javascript" language="javascript"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
  </body>
</html>